[package]
name = "proj"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
core_simd = { git = "https://github.com/rust-lang/portable-simd" }

# [profile.dev]
# opt-level = 0
# overflow-checks = false